services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./beckend 
    ports:
      - "3483:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/depl
      - PORT=3000
      - SECRET_JWT=gihojpcjcnjciujk16653527G
    depends_on:
      - mongo

volumes:
  mongo-data: