name: CI/CD Backend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: ./beckend
      run: npm ci

    - name: Run tests (test script)
      working-directory: ./beckend
      run: echo "No tests yet"

    - name: Build Docker image
      working-directory: ./beckend
      run: docker build -t auth-backend .

    - name: Run Docker Compose
      working-directory: ./beckend
      run: docker compose up -d
