name: CI/CD Backend

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./beckend
        run: npm ci

      - name: Run tests (test script)
        working-directory: ./beckend
        run: echo "No tests yet"

      - name: Build Docker image
        working-directory: ./beckend
        run: docker build -t auth-backend .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag auth-backend ${{ secrets.DOCKER_USERNAME }}/auth-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-backend:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'devops-learning-backend'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: '${{ secrets.DOCKER_USERNAME }}/auth-backend:latest'
